image: tiangolo/docker-with-compose

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - deploy

build-prod:
  stage: build
  variables:
    DB_PASSWORD: $DB_PASSWORD
    BUSINESS_MAIL: $BUSINESS_MAIL
    SENDGRID_API_KEY: $SENDGRID_API_KEY
    AUTH_JWT_SECRET: $AUTH_JWT_SECRET
  script:
    - docker-compose -f production.yml build
    - docker-compose -f production.yml push
  only:
    - develop
  tags:
    - build

deploy-prod:
  stage: deploy
  script:
    - docker info
    - docker stack deploy -c production.yml --with-registry-auth plus-medical  #plus-medical is stack name 
  only:
    - develop
  tags:
    - build
