image: docker:19.03.9-dind

variables:
  DOCKER_DRIVER: overlay2
  # Create the certificates inside this directory for both the server
  # and client. The certificates used by the client will be created in
  # /certs/client so we only need to share this directory with the
  # volume mount in `config.toml`.
  DOCKER_TLS_CERTDIR: "/certs"

services:
    - docker:19.03.0-dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - deploy

build-prod:
  stage: build
  script:
    - docker-compose -f production.yml build
    - docker-compose -f production.yml push
  only:
    - develop
  tags:
    - build

deploy-prod:
  stage: deploy
  script:
    - docker stack deploy -c production.yml --with-registry-auth backend
  only:
    - master
  tags:
    - build
