version: '3.3'

volumes:
  local_couchbase_data: {}

services:
  api:
    build:
      context: .
      dockerfile: ./compose/local/api/Dockerfile
    image: backend_local_api
    depends_on:
      - db
    command: 
      - /bin/sh
      - -c
      - |
        echo "sleep for 60sec"
        sleep 60 
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  db:
    image: couchbase:enterprise-6.5.1
    ports:
      - '8091-8094:8091-8094'
      - '11210:11210'
    volumes:
      - local_couchbase_data:/opt/couchbase/var/lib/couchbase
