version: '3.3'

volumes:
  local_couchbase_data: {}

services:
  api:
    build:
      context: .
      dockerfile: ./compose/production/api/Dockerfile
    image: '${CI_REGISTRY_IMAGE}/backend_local_api:latest'
    environment:
      - DB_NAME=platzi-store
      - DB_PASSWORD='${DB_PASSWORD}'
      - DB_URL=couchbase://db
      - DB_NAME=plus-medical
      - BUSINESS_MAIL='${BUSINESS_MAIL}'
      - SENDGRID_API_KEY='${SENDGRID_API_KEY}'
      - AUTH_JWT_SECRET='${AUTH_JWT_SECRET}'
      - DISABLE_SENDMAIL='${DISABLE_SENDMAIL}'
      - S3_BUCKET='${S3_BUCKET}'
      - S3_ACCESS_KEY_ID='${S3_ACCESS_KEY_ID}'
      - S3_SECRET_ACCESS_KEY='${S3_SECRET_ACCESS_KEY}'
    networks:
      - traefik-public
      - default
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.plus-medical-api-http.rule=Host(`api.plus-medical.co`)
        - traefik.http.routers.plus-medical-api-http.entrypoints=http
        - traefik.http.routers.plus-medical-api-http.middlewares=plus-medical-https-redirect
        - traefik.http.routers.plus-medical-api-https.rule=Host(`api.plus-medical.co`)
        - traefik.http.routers.plus-medical-api-https.entrypoints=https
        - traefik.http.routers.plus-medical-api-https.tls=true
        - traefik.http.routers.plus-medical-api-https.tls.certresolver=le
        - traefik.http.services.plus-medical-api.loadbalancer.server.port=3000
    depends_on:
      - db
    command: ['.scripts/wait.sh', 'db:8091', '--', 'npm', 'start']
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  db:
    image: couchbase:enterprise-6.5.1
    ports:
      - '11210:11210'
    networks:
      - traefik-public
      - default
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.plus-medical-db-http.rule=Host(`db.plus-medical.co`)
        - traefik.http.routers.plus-medical-db-http.entrypoints=http
        - traefik.http.routers.plus-medical-db-http.middlewares=plus-medical-https-redirect
        - traefik.http.routers.plus-medical-db-https.rule=Host(`db.plus-medical.co`)
        - traefik.http.routers.plus-medical-db-https.entrypoints=https
        - traefik.http.routers.plus-medical-db-https.tls=true
        - traefik.http.routers.plus-medical-db-https.tls.certresolver=le
        - traefik.http.services.plus-medical-db.loadbalancer.server.port=8091
    volumes:
      - local_couchbase_data:/opt/couchbase/var/lib/couchbase

networks:
  traefik-public:
    external: true
